# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './my_widgets/history_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryWidget(object):
    def setupUi(self, HistoryWidget):
        HistoryWidget.setObjectName("HistoryWidget")
        HistoryWidget.resize(500, 390)
        HistoryWidget.setMinimumSize(QtCore.QSize(500, 390))
        self.verticalLayoutWidget = QtWidgets.QWidget(HistoryWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.startDateTimeEdit = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.startDateTimeEdit.setObjectName("startDateTimeEdit")
        self.gridLayout.addWidget(self.startDateTimeEdit, 2, 0, 1, 1)
        self.endDateTimeEdit = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.endDateTimeEdit.setObjectName("endDateTimeEdit")
        self.gridLayout.addWidget(self.endDateTimeEdit, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pastScrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.pastScrollArea.setWidgetResizable(True)
        self.pastScrollArea.setObjectName("pastScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 477, 250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pastScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.pastScrollArea)

        self.retranslateUi(HistoryWidget)
        QtCore.QMetaObject.connectSlotsByName(HistoryWidget)

    def retranslateUi(self, HistoryWidget):
        _translate = QtCore.QCoreApplication.translate
        HistoryWidget.setWindowTitle(_translate("HistoryWidget", "Form"))
        self.label_2.setText(_translate("HistoryWidget", "Начало поиска:"))
        self.label.setText(_translate("HistoryWidget", "Конец поиска:"))
        self.pushButton.setText(_translate("HistoryWidget", "Искать"))
