# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './my_widgets/statistic_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatisticWidget(object):
    def setupUi(self, StatisticWidget):
        StatisticWidget.setObjectName("StatisticWidget")
        StatisticWidget.resize(449, 559)
        self.verticalLayoutWidget = QtWidgets.QWidget(StatisticWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 451, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textStatisticLayout = QtWidgets.QVBoxLayout()
        self.textStatisticLayout.setObjectName("textStatisticLayout")
        self.verticalLayout.addLayout(self.textStatisticLayout)
        self.graphStatisticWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.graphStatisticWidget.setObjectName("graphStatisticWidget")
        self.verticalLayout.addWidget(self.graphStatisticWidget)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 5)

        self.retranslateUi(StatisticWidget)
        QtCore.QMetaObject.connectSlotsByName(StatisticWidget)

    def retranslateUi(self, StatisticWidget):
        _translate = QtCore.QCoreApplication.translate
        StatisticWidget.setWindowTitle(_translate("StatisticWidget", "Form"))
        self.label.setText(_translate("StatisticWidget", "Промежуток времени:"))
        self.comboBox.setItemText(0, _translate("StatisticWidget", "День"))
        self.comboBox.setItemText(1, _translate("StatisticWidget", "Неделя"))
        self.comboBox.setItemText(2, _translate("StatisticWidget", "Полмесяца"))
        self.comboBox.setItemText(3, _translate("StatisticWidget", "Месяц"))
        self.comboBox.setItemText(4, _translate("StatisticWidget", "Квартал"))
        self.comboBox.setItemText(5, _translate("StatisticWidget", "Полугодие"))
        self.comboBox.setItemText(6, _translate("StatisticWidget", "Год"))
