# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(490, 260)
        Frame.setMinimumSize(QtCore.QSize(490, 260))
        Frame.setStyleSheet("QPushButton{\n"
"    border-radius: 0;\n"
"}")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 489, 273))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upVerticalLayout = QtWidgets.QVBoxLayout()
        self.upVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.upVerticalLayout.setObjectName("upVerticalLayout")
        self.upHorizontalLayout = QtWidgets.QHBoxLayout()
        self.upHorizontalLayout.setObjectName("upHorizontalLayout")
        self.taskNameEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.taskNameEdit.setObjectName("taskNameEdit")
        self.upHorizontalLayout.addWidget(self.taskNameEdit)
        self.upVerticalLayout.addLayout(self.upHorizontalLayout)
        self.startTaskButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.startTaskButton.setObjectName("startTaskButton")
        self.upVerticalLayout.addWidget(self.startTaskButton)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_doing = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_doing.setObjectName("label_doing")
        self.gridLayout.addWidget(self.label_doing, 0, 1, 1, 1)
        self.dateTimeStart = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget_2)
        self.dateTimeStart.setObjectName("dateTimeStart")
        self.gridLayout.addWidget(self.dateTimeStart, 1, 0, 1, 1)
        self.label_start = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_start.setObjectName("label_start")
        self.gridLayout.addWidget(self.label_start, 0, 0, 1, 1)
        self.timeDoing = QtWidgets.QTimeEdit(self.verticalLayoutWidget_2)
        self.timeDoing.setObjectName("timeDoing")
        self.gridLayout.addWidget(self.timeDoing, 1, 1, 1, 1)
        self.addTaskButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.addTaskButton.setObjectName("addTaskButton")
        self.gridLayout.addWidget(self.addTaskButton, 1, 2, 1, 1)
        self.upVerticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.upVerticalLayout)
        self.bottomVerticalLayout = QtWidgets.QVBoxLayout()
        self.bottomVerticalLayout.setSpacing(0)
        self.bottomVerticalLayout.setObjectName("bottomVerticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background: \"#CCC\";\n"
"    border-width: 3 3 3 3;\n"
"    border-style: solid none none solid;\n"
"    border-color: \"#BBB\";\n"
"}\n"
"QPushButton:hover {\n"
"    background: \"#BBB\";\n"
"}\n"
"QPushButton:focus {\n"
"    background: \"#BBB\";\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: \"#CCC\";\n"
"    border-width: 3 3 3 3;\n"
"    border-style: solid none none solid;\n"
"    border-color: \"#BBB\";\n"
"}\n"
"QPushButton:hover {\n"
"    background: \"#BBB\";\n"
"}\n"
"QPushButton:focus {\n"
"    background: \"#BBB\";\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.bottomVerticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea.setStyleSheet("background: \"#DDD\";\n"
"border: None;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 477, 108))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.bottomVerticalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.bottomVerticalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.taskNameEdit, self.startTaskButton)
        Frame.setTabOrder(self.startTaskButton, self.dateTimeStart)
        Frame.setTabOrder(self.dateTimeStart, self.timeDoing)
        Frame.setTabOrder(self.timeDoing, self.addTaskButton)
        Frame.setTabOrder(self.addTaskButton, self.pushButton)
        Frame.setTabOrder(self.pushButton, self.pushButton_2)
        Frame.setTabOrder(self.pushButton_2, self.scrollArea)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.startTaskButton.setText(_translate("Frame", "Начать сейчас"))
        self.label_doing.setText(_translate("Frame", "Время выполнения"))
        self.label_start.setText(_translate("Frame", "Время начала:"))
        self.addTaskButton.setText(_translate("Frame", "Добавить"))
        self.pushButton.setText(_translate("Frame", "PushButton"))
        self.pushButton_2.setText(_translate("Frame", "PushButton"))
